//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STNDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class instrument_status
    {
        public int instrument_status_id { get; set; }
        public Nullable<int> status_type_id { get; set; }
        public Nullable<int> instrument_id { get; set; }
        public Nullable<System.DateTime> time_stamp { get; set; }
        public string notes { get; set; }
        public string time_zone { get; set; }
        public Nullable<int> member_id { get; set; }
        public Nullable<double> sensor_elevation { get; set; }
        public Nullable<double> ws_elevation { get; set; }
        public Nullable<double> gs_elevation { get; set; }
        public Nullable<int> vdatum_id { get; set; }
    
        public virtual instrument instrument { get; set; }
        public virtual status_type status_type { get; set; }
    }
}
