//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STNDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class op_control_identifier
    {
        public int op_control_identifier_id { get; set; }
        public Nullable<int> objective_point_id { get; set; }
        public string identifier { get; set; }
        public string identifier_type { get; set; }
    }
}
