//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STNDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class op_measurements
    {
        public int op_measurements_id { get; set; }
        public int objective_point_id { get; set; }
        public int instrument_status_id { get; set; }
        public Nullable<double> from_rp { get; set; }
        public Nullable<double> hanging_length { get; set; }
        public Nullable<double> water_surface { get; set; }
        public Nullable<double> ground_surface { get; set; }
        public string type { get; set; }
        public Nullable<double> offset_correction { get; set; }
    }
}
