//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STNDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class reportmetric_contact
    {
        public int reportmetric_contact_id { get; set; }
        public int reporting_metrics_id { get; set; }
        public int contact_id { get; set; }
        public int contact_type_id { get; set; }
    
        public virtual contact_type contact_type { get; set; }
        public virtual contact contact { get; set; }
        public virtual reporting_metrics reporting_metrics { get; set; }
    }
}
