//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STNDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class site
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public site()
        {
            this.hwms = new HashSet<hwm>();
            this.files = new HashSet<file>();
            this.instruments = new HashSet<instrument>();
            this.objective_points = new HashSet<objective_point>();
            this.site_housing = new HashSet<site_housing>();
            this.network_type_site = new HashSet<network_type_site>();
            this.network_name_site = new HashSet<network_name_site>();
        }
    
        public int site_id { get; set; }
        public string site_no { get; set; }
        public string site_name { get; set; }
        public string site_description { get; set; }
        public string address { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public string zip { get; set; }
        public string other_sid { get; set; }
        public string county { get; set; }
        public string waterbody { get; set; }
        public double latitude_dd { get; set; }
        public double longitude_dd { get; set; }
        public int hdatum_id { get; set; }
        public Nullable<double> drainage_area_sqmi { get; set; }
        public Nullable<int> landownercontact_id { get; set; }
        public Nullable<int> priority_id { get; set; }
        public string zone { get; set; }
        public string is_permanent_housing_installed { get; set; }
        public string usgs_sid { get; set; }
        public string noaa_sid { get; set; }
        public Nullable<int> hcollect_method_id { get; set; }
        public string site_notes { get; set; }
        public string safety_notes { get; set; }
        public string access_granted { get; set; }
        public Nullable<int> member_id { get; set; }
        public Nullable<int> sensor_not_appropriate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hwm> hwms { get; set; }
        public virtual horizontal_datums horizontal_datums { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<file> files { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<instrument> instruments { get; set; }
        public virtual deployment_priority deployment_priority { get; set; }
        public virtual landownercontact landownercontact { get; set; }
        public virtual horizontal_collect_methods horizontal_collect_methods { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<objective_point> objective_points { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<site_housing> site_housing { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<network_type_site> network_type_site { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<network_name_site> network_name_site { get; set; }
        public virtual member member { get; set; }
    }
}
