//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STNDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class site_housing
    {
        public int site_housing_id { get; set; }
        public Nullable<int> site_id { get; set; }
        public Nullable<int> housing_type_id { get; set; }
        public Nullable<double> length { get; set; }
        public string material { get; set; }
        public string notes { get; set; }
        public Nullable<double> amount { get; set; }
    
        public virtual site site { get; set; }
    }
}
