//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STNDB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class STNDBEntities : DbContext
    {
        public STNDBEntities()
            : base("name=STNDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<agency> agencies { get; set; }
        public virtual DbSet<approval> approvals { get; set; }
        public virtual DbSet<contact> contacts { get; set; }
        public virtual DbSet<contact_type> contact_type { get; set; }
        public virtual DbSet<county> counties { get; set; }
        public virtual DbSet<data_file> data_file { get; set; }
        public virtual DbSet<deployment_priority> deployment_priority { get; set; }
        public virtual DbSet<deployment_type> deployment_type { get; set; }
        public virtual DbSet<event_status> event_status { get; set; }
        public virtual DbSet<event_type> event_type { get; set; }
        public virtual DbSet<events> events { get; set; }
        public virtual DbSet<file_keyword> file_keyword { get; set; }
        public virtual DbSet<file_type> file_type { get; set; }
        public virtual DbSet<file> files { get; set; }
        public virtual DbSet<horizontal_collect_methods> horizontal_collect_methods { get; set; }
        public virtual DbSet<horizontal_datums> horizontal_datums { get; set; }
        public virtual DbSet<housing_type> housing_type { get; set; }
        public virtual DbSet<hwm> hwms { get; set; }
        public virtual DbSet<hwm_qualities> hwm_qualities { get; set; }
        public virtual DbSet<hwm_types> hwm_types { get; set; }
        public virtual DbSet<instr_collection_conditions> instr_collection_conditions { get; set; }
        public virtual DbSet<instrument> instruments { get; set; }
        public virtual DbSet<instrument_status> instrument_status { get; set; }
        public virtual DbSet<landownercontact> landownercontacts { get; set; }
        public virtual DbSet<locatortype> locatortypes { get; set; }
        public virtual DbSet<marker> markers { get; set; }
        public virtual DbSet<network_name> network_name { get; set; }
        public virtual DbSet<network_name_site> network_name_site { get; set; }
        public virtual DbSet<network_type> network_type { get; set; }
        public virtual DbSet<network_type_site> network_type_site { get; set; }
        public virtual DbSet<objective_point> objective_point { get; set; }
        public virtual DbSet<objective_point_type> objective_point_type { get; set; }
        public virtual DbSet<op_control_identifier> op_control_identifier { get; set; }
        public virtual DbSet<op_measurements> op_measurements { get; set; }
        public virtual DbSet<op_quality> op_quality { get; set; }
        public virtual DbSet<peak_summary> peak_summary { get; set; }
        public virtual DbSet<reporting_metrics> reporting_metrics { get; set; }
        public virtual DbSet<reportmetric_contact> reportmetric_contact { get; set; }
        public virtual DbSet<role> roles { get; set; }
        public virtual DbSet<sensor_brand> sensor_brand { get; set; }
        public virtual DbSet<sensor_deployment> sensor_deployment { get; set; }
        public virtual DbSet<sensor_type> sensor_type { get; set; }
        public virtual DbSet<site_housing> site_housing { get; set; }
        public virtual DbSet<site> sites { get; set; }
        public virtual DbSet<source> sources { get; set; }
        public virtual DbSet<state> states { get; set; }
        public virtual DbSet<status_type> status_type { get; set; }
        public virtual DbSet<vertical_collect_methods> vertical_collect_methods { get; set; }
        public virtual DbSet<vertical_datums> vertical_datums { get; set; }
        public virtual DbSet<member> members { get; set; }
    }
}
